# Generated by Django 3.1.3 on 2021-10-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_adminnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
