# Generated by Django 3.1.3 on 2021-09-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210917_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFeedback',
        ),
    ]
