# Generated by Django 3.1.3 on 2021-09-17 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_delete_studentfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=100000)),
                ('appied_date', models.DateTimeField(blank=True, default=datetime.datetime)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.student_data')),
            ],
        ),
    ]
