# Generated by Django 3.1.3 on 2021-09-17 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentsfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsfeedback',
            name='appied_date',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
