# Generated by Django 3.1.3 on 2021-09-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20210920_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='class_division',
            field=models.CharField(default='FY', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Class_Division',
        ),
    ]
