# Generated by Django 3.1.3 on 2021-10-10 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20210920_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student_data'),
        ),
        migrations.AlterField(
            model_name='studentsfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student_data'),
        ),
    ]
